services:
  - type: web
    name: english-tutor-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -w 4 -t 60 main:app
